#this workflow will build a java project with maven

name: Java CI with Maven in Linux

on:
 push:
 pull_request:
 
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@v3
  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
     distribution: 'temurin'
     java-version: '17'
  - name: Cache maven m2 folder
    uses: actions/cache@v2
    with:
     path: $HOME/.m2
     key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml')}}
     restor-keys: ${{runner.os}}-m2-
  - name: Build with Maven
    run: mvn -f exercise/pom.xml clean verify
